version: "2"
services:
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: library_db
            MYSQL_USER: root
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
  
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8004:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
        depends_on: 
            - db
